# Generated by Django 5.0.3 on 2024-03-12 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="typesell",
            name="product",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type_product",
                to="product.product",
            ),
            preserve_default=False,
        ),
    ]
