# Generated by Django 5.0.3 on 2024-03-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True, max_length=11, verbose_name="Phone Number"
                    ),
                ),
                ("code", models.PositiveSmallIntegerField(verbose_name="Code")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Active Code",
                "verbose_name_plural": "Active codes",
                "db_table_comment": "otp table is for verify code of number 1000 to 9999",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        max_length=11,
                        unique=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=180, unique=True, verbose_name="Email"
                    ),
                ),
                ("is_admin", models.BooleanField(default=False, verbose_name="Admin")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("date_birth", models.DateField(verbose_name="Date Birth")),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table_comment": "custom user model with row attribute(AbstractBaseUser)",
            },
        ),
    ]
