# Generated by Django 5.0.3 on 2024-03-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpcode",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Created Date_Time"
            ),
        ),
    ]
